[[IgnoredVulns]]
id = "GHSA-cj8j-37rh-8475"
reason = "Awaiting release of fix from transient dependency"

[[IgnoredVulns]]
id = "GHSA-wg6q-6289-32hp"
reason = "Awaiting release of fix from transient dependency"
